spring:
  application:
    name: recruiter
  servlet:
    multipart:
      enabled: true
      max-file-size: 5MB
      max-request-size: 100MB

server:
  port: 8080

recruitment:
  shortlist-count: 3
  max-job-description-words: 1000
  max-candidates: 20
  max-file-size-bytes: 5242880  # 5 MB
